### ISSUE TITLE
Jumplists don't seem to be working

### ISSUE THREAD

**Issue by wererogue** [VsVim/VsVim#1621]
Hi, I'm using 1.8.0.0 and I've been annoyed by visual studio's navigation so I wanted to see if VsVim's jumplists were working well (I've used them in Vim, just didn't think to check for VsVim). ctrl-o and ctrl-i don't seem to be doing anything even though they're assigned to VsVim in the VsVim settings, and :jumps shows "Parse error".

ctrl-o isn't mapped to anything in Visual Studio and ctrl-i isn't mapped to anything related to the text editor.

**Comment by jaredpar** [comment]
Jump lists have some support in VsVim but it's mostly limited to the following:

- Other features, like mark jumping, maintain the internal jump list.
- The <kbd>`</kbd> mark does grab the last jump location. 

VsVim hasn't hooked the jump list to the <kbd>Ctrl+O</kbd> and <kbd>Ctrl+I</kbd> commands though nor has it implemented the `:jumps` command .  I can look into doing that.

**Comment by wererogue** [comment]
Oh, I got the impression it'd once been working from this issue: https://github.com/jaredpar/VsVim/issues/485

I'll look forward to using them in future, thank you!

**Comment by jaredpar** [comment]
@wererogue actually I have implemented <kbd>Ctrl+O</kbd> and <kbd>Ctrl+I<kbd> for jump list.  I was just looking at the wrong part of the code and thought I had omitted it.  I did just check and both commands are working for me.  For example I did the following:

- Set a mark in the file via `mc`
- moved away 
- Jumped back with `'c`
- Used <kbd>Ctrl+O</kbd> to jump back to location in the second step.

**Comment by wererogue** [comment]
Yup, you're right - that seems to be working fine.  I think maybe I was using a bad test case - I thought switching file would add to the jump list, but of course it doesn't at all.

Having :jumps would still be great, thanks! :)

**Comment by haolly** [comment]
Until version 2.4 release, the jumplist is still not work, miss this feature so much

**Comment by erihanse** [comment]
It would be nice if this worked between files. So if you `gd` to look up a definition which recides in another file, you can `CTRL-O` to go back to where you were when you looked it up.

**Comment by ricksladkey** [comment]
The jump lists have been implemented for a long time (several years). However as with vim, they are confined to, as vim calls it, a single "window" (`:help jump` in vim). I am not sure why some people are unable to get jump lists to work. Perhaps there are bugs where VsVim fails to feed the jump list and then it appears not to work.

In any case, if you want to jumps to work cross-file (unlike vim), you can use the navigate forward/backward feature of Visual Studio, which also works well. These can be assigned to the normal `<C-o>` and `<C-i>` jump list keys as follows:

```
nmap <C-O> :vsc View.NavigateBackward<CR>
nmap <C-I> :vsc View.NavigateForward<CR>
vmap <C-O> :vsc View.NavigateBackward<CR>
vmap <C-I> :vsc View.NavigateForward<CR>
```

**Comment by CrispyDrone** [comment]
When I use Ctrl-[ to go to a definition and it is in another file, Ctrl-O does not work.
In fact, Ctrl-O and Ctrl-I for me only work inside a single file.

Something telling is that when I have a jump list within a single file, and then use Ctrl-[ to navigate to a definition, Ctrl-O will work but it will jump back to the last entry of the jump list of that file. So it means it did not append the go to definition jump to the jump list.

Would it be possible to investigate this issue once more? It seems quite a few people are (still?) having issues with it. 

If you need any additional information, don't hesitate to ask of course. Thank you for all your hard work.

**Comment by ricksladkey** [comment]
@CrispyDrone, I am going to close this issue because jump lists are fully implemented and because they are fully compatible with vim. I tested your specific case and go to definition jump definitely adds a jump to the jump list which is exactly what the code says to do:

```fsharp
        if _vimHost.GoToDefinition() then
            _jumpList.Add before
            Result.Succeeded
```

Feel free to open a new issue for this if you believe something is not working.
